modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
logoFile = "logo.png"
modId = "legacybob"
version = "${version}"
displayName = "LegacyBob"
authors = "ABU009"
displayURL = "https://github.com/ABU008/Legacy-Bob"
description = '''
ViewBobbing from 1.12 and below!
'''

[[dependencies.legacybob]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legacybob]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1, )"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "legacybob.mixins.json"
